//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5456
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIDS2008R2Downgrade {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BIDS2008R2Downgrade.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The built-in field {OldFieldName}, used by element &apos;{0}&apos;, is not supported by SQL Server 2008 Reporting Services. Either reduce the error level to a value less than 3 to replace it automatically with {NewFieldName}, remove the built-in field from the report or change the ReportServerTargetVersion to a version that supports the {OldFieldName} build-in field..
        /// </summary>
        internal static string ErrorBuiltInField {
            get {
                return ResourceManager.GetString("ErrorBuiltInField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The state indicator, {0}, was detected in the report. SQL Server 2008 Reporting Services does not support state indicators. Either reduce the error level to a value less than 2 or change the ReportServerTargetVersion to a version that supports state indicators..
        /// </summary>
        internal static string ErrorIndicator {
            get {
                return ResourceManager.GetString("ErrorIndicator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The map, {0}, was detected in the report. SQL Server 2008 Reporting Services does not support map report items. Either reduce the error level to a value less than 2 or change the ReportServerTargetVersion to a version that supports map report items..
        /// </summary>
        internal static string ErrorMap {
            get {
                return ResourceManager.GetString("ErrorMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An attempt has been made to use a data extension &apos;SHAREPOINTLIST&apos;, &apos;SQLAZURE&apos; or &apos;SQLPDW&apos; that is either not registered for this report server or is not supported in this edition of Reporting Services..
        /// </summary>
        internal static string ErrorNewDataSource {
            get {
                return ResourceManager.GetString("ErrorNewDataSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A PageBreak property was detected in the data region, rectangle, or group ‘{0}’ SQL Server 2008 Reporting Services does not support the PageBreak property, Disabled or ResetPageNumber. Either reduce the error level to a value less than 3 or change the ReportServerTargetVersion to a version that supports the PageBreak property Disabled or ResetPageNumber..
        /// </summary>
        internal static string ErrorNewPageBreakOptions {
            get {
                return ResourceManager.GetString("ErrorNewPageBreakOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The WritingMode value &apos;Rotate270&apos; of element &apos;{0}&apos; is not supported in SQL Server 2008 Reporting Services. Set the WritingMode to either &apos;Horizontal&apos; or &apos;Vertical&apos; or change the ReportServerTargetVersion to a version that supports a WritingMode of &apos;Rotate270&apos;..
        /// </summary>
        internal static string ErrorRotate270 {
            get {
                return ResourceManager.GetString("ErrorRotate270", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data set, {0}, is a shared dataset. SQL Server 2008 Reporting Services does not support shared data sets..
        /// </summary>
        internal static string ErrorSharedDataset {
            get {
                return ResourceManager.GetString("ErrorSharedDataset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Writeable property of variable, WritableVariable, is set to true on variable &apos;{0}&apos;. SQL Server 2008 Reporting Services does not support variables that are read/write. Either make the variable read-only or change the ReportServerTargetVersion to a version that supports the read/write variables..
        /// </summary>
        internal static string ErrorWritableVariable {
            get {
                return ResourceManager.GetString("ErrorWritableVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Built-in field {OldFieldName} was replaced by {NewFieldName} for element &apos;{0}&apos;. SQL Server 2008 Reporting Services does not support the {OldFieldName} built-in field..
        /// </summary>
        internal static string WarningBuiltInField {
            get {
                return ResourceManager.GetString("WarningBuiltInField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - Element of type &apos;{1}&apos;, part of &apos;{2}&apos; named &apos;{3}&apos; was removed or modified. 
        ///XPath that was used to find the element: {4}..
        /// </summary>
        internal static string WarningGeneric {
            get {
                return ResourceManager.GetString("WarningGeneric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The state indicator, {0}, was removed from the report. SQL Server 2008 Reporting Services does not support state indicators..
        /// </summary>
        internal static string WarningIndicator {
            get {
                return ResourceManager.GetString("WarningIndicator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The map, {0}, was removed from the report. SQL Server 2008 Reporting Services does not support map report items..
        /// </summary>
        internal static string WarningMap {
            get {
                return ResourceManager.GetString("WarningMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data source, {0}, was removed from the report. SQL Server 2008 Reporting Services does not support data sources of type &apos;SHAREPOINTLIST&apos;, &apos;SQLAZURE&apos; or &apos;SQLPDW&apos;..
        /// </summary>
        internal static string WarningNewDataSource {
            get {
                return ResourceManager.GetString("WarningNewDataSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A PageBreak property was removed from the data region, rectangle, or group ‘{0}’. SQL Server 2008 Reporting Services does not support the PageBreak property Disabled or ResetPageNumber..
        /// </summary>
        internal static string WarningNewPageBreakOptions {
            get {
                return ResourceManager.GetString("WarningNewPageBreakOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The WritingMode value &apos;Rotate270&apos; of element &apos;{0}&apos; was changed to &apos;Vertical&apos;. SQL Server 2008 Reporting Services does not support the &apos;Rotate270&apos; WritingMode value..
        /// </summary>
        internal static string WarningRotate270 {
            get {
                return ResourceManager.GetString("WarningRotate270", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The shared dataset, {0}, was removed from the report. SQL Server 2008 Reporting Services does not support shared data sets..
        /// </summary>
        internal static string WarningSharedDataset {
            get {
                return ResourceManager.GetString("WarningSharedDataset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Writable property of variable {0} was removed from the report. SQL Server 2008 Reporting Services does not writable variables..
        /// </summary>
        internal static string WarningWritableVariable {
            get {
                return ResourceManager.GetString("WarningWritableVariable", resourceCulture);
            }
        }
    }
}
